### PR TITLE
OpenAI-DotNet 7.3.6

### LINKED ISSUE #189: Chat completion streaming with multiple tools results throws ArgumentOutOfRangeException
# Bug Report

I'm back with another bug 😅

## Overview
Chat completion throws error when streaming and multiple tools are returned by the API

## To Reproduce
```cs
            var messages = new List<Message>
            {
                new Message(Role.System, "You are a helpful weather assistant."),
                new Message(Role.User, "What's the weather like today in San Diego and LA?"),
            };

            var tools = new List<Tool>
            {
                new Function(
                    nameof(WeatherService.GetCurrentWeather),
                    "Get the current weather in a given location",
                    new JsonObject
                    {
                        ["type"] = "object",
                        ["properties"] = new JsonObject
                        {
                            ["location"] = new JsonObject
                            {
                                ["type"] = "string",
                                ["description"] = "The city and state, e.g. San Francisco, CA"
                            },
                            ["unit"] = new JsonObject
                            {
                                ["type"] = "string",
                                ["enum"] = new JsonArray { "celsius", "fahrenheit" }
                            }
                        },
                        ["required"] = new JsonArray { "location", "unit" }
                    })
            };

            var chatRequest = new ChatRequest(messages, model: "gpt-4-1106-preview", tools: tools, toolChoice: "auto");

            var response = await OpenAIClient.ChatEndpoint.StreamCompletionAsync(chatRequest, _ =>
            {
            });

            var toolCalls = response.FirstChoice.Message.ToolCalls;

            foreach (var toolCall in toolCalls)
            {
                messages.Add(new Message(toolCall, "Sunny!"));
            }

            chatRequest = new ChatRequest(messages, model: "gpt-4-1106-preview", tools: tools, toolChoice: "auto");
            response = await OpenAIClient.ChatEndpoint.GetCompletionAsync(chatRequest);
```

## Expected behavior
No exception is thrown

### PR DESCRIPTION
**Pull request by Mitch528**
- Fixed ArgumentOutOfRangeException when streaming chat completion response contains more than one tool

### CODE REVIEW

**Comment by Mitch528** [comment]
> I'm still not sure the changes make sense to me.
> 
> Can you briefly explain the changes?

Before the change, it attempted to set `toolCalls[otherToolCall.Index.Value]` which is outside of the range of the list

> System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

```cs
                        if (toolCalls.Count == 0)
                        {
                            toolCalls.Insert(otherToolCall.Index.Value, new Tool(otherToolCall));
                        }
                        else
                        {
                            toolCalls[otherToolCall.Index.Value].CopyFrom(otherToolCall); // Exception occurs here
                        }
```

**Comment by StephenHodgson** [comment]
And the new changes?

**Comment by Mitch528** [comment]
> And the new changes?

Inserts into the list first before attempting to set the index.

**Comment by StephenHodgson** [comment]
Perfect thanks. Please update the change log and update the version

**Comment by Mitch528** [comment]
> Perfect thanks. Please update the change log and update the version

Updated!

**Pull request merged**
