### PR TITLE
OpenAI-DotNet 6.7.1

### PR DESCRIPTION
**Pull request by StephenHodgson**
- Clarify authentication documentation with recommended usage of API keys
- [Fixed parsing old env file format](#82)
- Fixed parsing missing ORGANIZATION env vars
- [Fixed checking of CancellationToken.IsCancellationRequested in streaming endpoints](#83)

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@ADefWebserver do you mind adding additional documentation about user secrets to this PR?

**Comment by ADefWebserver** [comment]
> @ADefWebserver do you mind adding additional documentation about user secrets to this PR from #80?

You are welcome to add the comments and screens shots that I made to that thread. If you want something better I will need a day. Let me know. Thanks

**Comment by ADefWebserver** [comment]
Thanks. I should be able to get something clear and easy to follow by tomorrow

**Comment by StephenHodgson** [comment]
You'll need to use your fork and open a PR against this branch @ADefWebserver

**Comment by StephenHodgson** [comment]
> Adding keys to a Microsoft Blazor Server application

I think this could apply to any asp.net project, no?

**Comment by ADefWebserver** [comment]
> > Adding keys to a Microsoft Blazor Server application
> 
> I think this could apply to any asp.net project, no?

Yes the title should be changed to "Adding keys to a .Net Core Application".

Do you still need me to make a PR?

**Comment by StephenHodgson** [comment]
If you'd like credit for the change, yes. Otherwise I can make the changes later

**Comment by ADefWebserver** [comment]
> If you'd like credit for the change, yes. Otherwise I can make the changes later

Its fine if you just make the change :)

**Pull request merged**
