### PR TITLE
OpenAI-DotNet 7.3.7

### PR DESCRIPTION
**Pull request by Mitch528**
- Fixes streaming with tools not being property copied over

### CODE REVIEW

**Comment by StephenHodgson** [comment]
update changelog and version

**Comment by StephenHodgson** [comment]
gonna pull and make sure tests pass this time 😅

**Comment by Mitch528** [comment]
> update changelog and version

done!

**Comment by Mitch528** [comment]
> gonna pull and make sure tests pass this time 😅

good idea 😓

**Review by StephenHodgson — APPROVED** [review]

**Comment by Mitch528** [comment]
@StephenHodgson doesn't seem to have been published to NuGet?

**Pull request merged**
